

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: server-storage


# GCP; the csi provisioner supports snapshots
#
# provisioner: kubernetes.io/gce-pd
provisioner: pd.csi.storage.gke.io

# AWS;
#
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2

# parameters:
#   type: pd-standard
#   # type: pd-ssd
#   replication-type: none


# ##################################

# Tanzu
# provisioner: kubernetes.io/aws-ebs



# volumeBindingMode: Immediate
volumeBindingMode: WaitForFirstConsumer

# reclaimPolicy: Delete
reclaimPolicy: Retain

#
# I added this line, so far, to no effect
#
allowVolumeExpansion: true





