# Sized to work on 3 k8s workers nodes with 1 core / 4 GB RAM
# See neighboring example-cassdc-full.yaml for docs for each parameter

apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:

  name: dc1
  namespace: ns-cass-sys2

spec:
  clusterName: cluster1

  serverType: cassandra
  serverVersion: "3.11.7"

  managementApiAuth:
    insecure: {}

#
#  I added this. Effectively; make a folder on the C* Pod
#
  initContainers:
  - name: backup-setup
    image: busybox:latest
    command: ['sh', '-c', " mkdir /var/lib/cassandra/staging_directory", "chmod 777 /var/lib/cassandra/staging_directory"]

  size: 1

  stopped: true

  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:    
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager

      #
      #  I added these
      #
#     backup_service:
#       enabled: true
#     staging_directory: /var/lib/cassandra/backups_staging

    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
      additional-jvm-opts:
        # As the database comes up for the first time, set system keyspaces to RF=3
        - "-Ddse.system_distributed_replication_dc_names=dc1"

#       - "-Ddse.system_distributed_replication_per_dc=3"
        - "-Ddse.system_distributed_replication_per_dc=1"





