#
#  This YAML is run from file 45*
#
#  See notes there for more information on use.
#

apiVersion: v1
kind: Pod
metadata:
  name: generic-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.19.5

    command: ["/bin/bash", "-c"]
    args:
    - |
      apt-get update
      apt-get install -y vim 
      apt-get install -y python
      apt-get install -y wget
      apt-get install -y default-jre
         #
      cd /opt
      curl -L https://downloads.apache.org/cassandra/4.0-beta4/apache-cassandra-4.0-beta4-bin.tar.gz | tar xz
      mv apache-cassandra-4.0-beta4 cassandra
         #
      #
      #  some Linux's do not support this argument to sleep
      #
      sleep infinity & wait

    ports:
    - containerPort: 80
    volumeMounts:
    - name: opt
      mountPath: /opt
  dnsPolicy: Default
  volumes:
  - name: opt
    emptyDir: {}



