

#
#  kubectl exec -i -t dnsutils -- nslookup    k8ssandra-dc1-stargate-service.ns-k8s
#  kubectl -n ns-user2 exec -i -t dnsutils -- sh
#

apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  # namespace: default
  # namespace: ns-k8s
  namespace: ns-user2
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always




